version: "3"
services:
    flask:
        build: .
        command: gunicorn -w 1 -b 0.0.0.0:5001 utm_builder:app --reload
        # command: flask run --host=0.0.0.0
        environment: 
            - FLASK_APP=utm_builder.py
            - FLASK_DEBUG=1
            - PYTHONBUFFERED=True
        ports:
            - "5001:5001"
        volumes:
            - ./:/root